[build]
  command = "npm install --legacy-peer-deps && npm run build-portfolio"
  publish = "dist/abFiras-portfolio"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200